#!/bin/bash
#batch file renamer
#change the content of the sed command depending on what needs to be changed in the list of filenames...

for file in * ; do
	$f =`echo $file` | sed -e 's/_-_/_/g'
	[ $file = $f ] || mv -i $file $f
done
